
checksum:
  algorithm: sha256
release:
  prerelease: auto
# archives:
#   - format: binary
#     replacements:
#       amd64: x86_64
#       darwin: macOS
builds:
  - main: ./cmd/hi
    binary: hi
    targets:
      - linux_amd64
    env:
      - CGO_ENABLED=1

    # not sure if I want this
    no_unique_dist_dir: true
