# .github/workflows/release.yaml

name: "Release"

on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.24
      with:
        build_command: make release
        # github_token: ${{ secrets.GITHUB_TOKEN }}
        github_token: ${{ github.token }}
        binary_name: hi
        goos: linux
        goarch: amd64

        # I'm not convinced you can actually do much authentication with a
        # crypto hash and no signature authority.  but we may as well use one
        # that actually matters if we're going to bother with it at all.
        md5sum: false
        sha256sum: true
