# .github/workflows/release.yaml

name: "Release"

on:
  release:
    types: [created]

jobs:
  release-matrix:
    name: Red Pill
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]

    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.24
      with:
        build_command: make release
        # github_token: ${{ secrets.GITHUB_TOKEN }}
        github_token: ${{ github.token }}
        binary_name: hi

        # from the matrix (above)
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}

        # I'm not convinced you can actually do much authentication with a
        # crypto hash and no signature authority. But we may as well use one
        # that actually matters if we're going to bother with it at all.
        md5sum: false
        sha256sum: true

        # If I re-create the tag or something, overwrite the asset. I fail to
        # see how this comes up unless I re-run it or something, but it feels
        # right to overwrite.
        overwrite: true
